"""initial_schema_13_tables

Revision ID: fcdee2f571c1
Revises: 
Create Date: 2026-09-06 16:00:55.165626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcdee2f571c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('airline_id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('airline_code', sa.String(length=3), nullable=False),
    sa.Column('airline_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('airline_id')
    )
    op.create_index(op.f('ix_airlines_airline_code'), 'airlines', ['airline_code'], unique=True)
    op.create_table('booking_windows',
    sa.Column('window_id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('window_code', sa.String(length=10), nullable=False),
    sa.Column('target_advance_days', sa.SmallInteger(), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('window_id'),
    sa.UniqueConstraint('target_advance_days'),
    sa.UniqueConstraint('window_code')
    )
    op.create_table('cities',
    sa.Column('city_id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('city_name', sa.String(length=80), nullable=False),
    sa.Column('state_name', sa.String(length=60), nullable=False),
    sa.Column('is_metro', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_cities_city_code'), 'cities', ['city_code'], unique=True)
    op.create_table('data_sources',
    sa.Column('source_id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_code', sa.String(length=30), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('source_code')
    )
    op.create_table('airports',
    sa.Column('airport_id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('city_id', sa.SmallInteger(), nullable=False),
    sa.Column('airport_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_index(op.f('ix_airports_city_id'), 'airports', ['city_id'], unique=False)
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('origin_city_id', sa.SmallInteger(), nullable=False),
    sa.Column('destination_city_id', sa.SmallInteger(), nullable=False),
    sa.Column('route_code', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('origin_city_id <> destination_city_id', name='ck_routes_origin_dest_different'),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.city_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.city_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('route_id'),
    sa.UniqueConstraint('origin_city_id', 'destination_city_id', name='uq_routes_origin_dest'),
    sa.UniqueConstraint('route_code')
    )
    op.create_table('base_period_fares',
    sa.Column('base_fare_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('base_period_code', sa.String(length=30), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.SmallInteger(), nullable=False),
    sa.Column('benchmark_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('methodology_notes', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['window_id'], ['booking_windows.window_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('base_fare_id'),
    sa.UniqueConstraint('base_period_code', 'route_id', 'window_id', name='uq_base_fares_period_route_window')
    )
    op.create_table('collection_runs',
    sa.Column('run_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('target_route_id', sa.Integer(), nullable=True),
    sa.Column('target_window_id', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_artifact_uri', sa.Text(), nullable=True),
    sa.Column('records_scraped', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_route_id'], ['routes.route_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_window_id'], ['booking_windows.window_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_runs_started_status', 'collection_runs', ['started_at', 'status'], unique=False)
    op.create_table('dgca_traffic_data',
    sa.Column('traffic_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('passengers_carried', sa.BigInteger(), nullable=False),
    sa.Column('flights_operated', sa.Integer(), nullable=True),
    sa.Column('report_source', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('traffic_id'),
    sa.UniqueConstraint('route_id', 'period_type', 'period_start', 'period_end', name='uq_dgca_traffic_route_period')
    )
    op.create_index('idx_dgca_route_dates', 'dgca_traffic_data', ['route_id', 'period_start', 'period_end'], unique=False)
    op.create_table('index_daily',
    sa.Column('index_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('base_period_code', sa.String(length=30), nullable=False),
    sa.Column('index_level', sa.String(length=20), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('window_id', sa.SmallInteger(), nullable=True),
    sa.Column('index_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('price_relative', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('formula_type', sa.String(length=30), nullable=False),
    sa.Column('routes_included', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("index_level IN ('NATIONAL_COMPOSITE', 'WINDOW_COMPOSITE', 'ROUTE_LEVEL')", name='ck_index_level_valid'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['window_id'], ['booking_windows.window_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('index_id')
    )
    op.create_index('idx_index_daily_query', 'index_daily', ['index_date', 'index_level', 'base_period_code'], unique=False)
    op.create_index('uq_index_daily_coalesce', 'index_daily', ['index_date', 'base_period_code', 'index_level', sa.literal_column('COALESCE(route_id, -1)'), sa.literal_column('COALESCE(window_id, -1)'), 'formula_type'], unique=True)
    op.create_table('route_daily_summary',
    sa.Column('summary_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.SmallInteger(), nullable=False),
    sa.Column('target_travel_date', sa.Date(), nullable=False),
    sa.Column('observations_count', sa.Integer(), nullable=False),
    sa.Column('min_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('median_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mean_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('geometric_mean_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('representative_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_imputed', sa.Boolean(), nullable=False),
    sa.Column('imputation_method', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['window_id'], ['booking_windows.window_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('observation_date', 'route_id', 'window_id', name='uq_route_daily_summary_obs_route_window')
    )
    op.create_index('idx_summary_lookup', 'route_daily_summary', ['observation_date', 'route_id', 'window_id'], unique=False)
    op.create_table('route_weights',
    sa.Column('weight_id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('base_period_code', sa.String(length=30), nullable=False),
    sa.Column('passenger_volume', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='ck_route_weight_range'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('weight_id'),
    sa.UniqueConstraint('route_id', 'base_period_code', name='uq_route_weights_route_base')
    )
    op.create_index('idx_weights_active', 'route_weights', ['base_period_code', 'is_active'], unique=False)
    op.create_table('fare_observations',
    sa.Column('observation_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_id', sa.SmallInteger(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.SmallInteger(), nullable=False),
    sa.Column('window_id', sa.SmallInteger(), nullable=False),
    sa.Column('flight_number', sa.String(length=15), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('advance_days', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_departure_time', sa.Time(), nullable=True),
    sa.Column('scheduled_arrival_time', sa.Time(), nullable=True),
    sa.Column('origin_airport_code', sa.String(length=3), nullable=True),
    sa.Column('destination_airport_code', sa.String(length=3), nullable=True),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('fare_family', sa.String(length=50), nullable=True),
    sa.Column('is_non_stop', sa.Boolean(), nullable=False),
    sa.Column('stops', sa.SmallInteger(), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fuel_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes_and_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('seats_remaining', sa.SmallInteger(), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_fare > 0', name='ck_fare_obs_total_fare_positive'),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.airline_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.source_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['window_id'], ['booking_windows.window_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('observation_id'),
    sa.UniqueConstraint('run_id', 'data_source_id', 'fingerprint_hash', name='uq_fare_obs_run_source_fingerprint')
    )
    op.create_index('idx_obs_fingerprint', 'fare_observations', ['fingerprint_hash'], unique=False)
    op.create_index('idx_obs_observed_at', 'fare_observations', ['observed_at'], unique=False)
    op.create_index('idx_obs_route_window_travel', 'fare_observations', ['route_id', 'window_id', 'travel_date', 'quality_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_obs_route_window_travel', table_name='fare_observations')
    op.drop_index('idx_obs_observed_at', table_name='fare_observations')
    op.drop_index('idx_obs_fingerprint', table_name='fare_observations')
    op.drop_table('fare_observations')
    op.drop_index('idx_weights_active', table_name='route_weights')
    op.drop_table('route_weights')
    op.drop_index('idx_summary_lookup', table_name='route_daily_summary')
    op.drop_table('route_daily_summary')
    op.drop_index('uq_index_daily_coalesce', table_name='index_daily')
    op.drop_index('idx_index_daily_query', table_name='index_daily')
    op.drop_table('index_daily')
    op.drop_index('idx_dgca_route_dates', table_name='dgca_traffic_data')
    op.drop_table('dgca_traffic_data')
    op.drop_index('idx_runs_started_status', table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_table('base_period_fares')
    op.drop_table('routes')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_city_id'), table_name='airports')
    op.drop_table('airports')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_cities_city_code'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('booking_windows')
    op.drop_index(op.f('ix_airlines_airline_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
